### ISSUE TITLE
far.predict_raster_binomial_iCAR

### ISSUE THREAD

**Issue by ricardozwarg** [ghislainv/forestatrisk#68]
Dear @ghislainv 

Could you please explain what is the forest_t3.tif that you have been used in the far.predict_raster_binomial_iCAR? I'm assuming that t1 in your example is forest in 2010, and t2 forest in 2020. So, what about t3? 

Thank you,

All the best

Ricardo.

**Comment by ghislainv** [comment]
@ricardozwarg, I assume your are speaking about the [Get Started](https://ecology.ghislainv.fr/forestatrisk/notebooks/get_started.html) tutorial? Please, try to be as specific as possible when raising an issue (in particular for other users interested in this issue too). In this tutorial, t1 is 2000, t2 is 2010, and t3 is 2020. Because I want the spatial probability of deforestation for year 2020 (t3), I need raster `forest_t3.tif` as input for the `far.predict_raster_binomial_iCAR()`.

**Comment by ricardozwarg** [comment]
Hi @ghislainv. Okay, now it make sense for me, so the fcc23 map in the Get Started tutorial is in fact the change between t2 and t3, instead of t1 and t2 that I was considering. Sorry about the confuse and I will try to be much more specifc in future questions.

All the best,
